Traceback (most recent call last):
  File "D:\GithubProject\MCV-C5-G3\Week1\Week1.py", line 176, in <module>
    model = best_model()
  File "D:\GithubProject\MCV-C5-G3\Week1\Week1.py", line 114, in __init__
    self.start1 = start()
  File "D:\GithubProject\MCV-C5-G3\Week1\Week1.py", line 66, in __init__
    he_initialization(self.conv1)
  File "D:\GithubProject\MCV-C5-G3\Week1\Week1.py", line 58, in he_initialization
    nn.init.zeros_(layer.fc1.bias)
  File "C:\Users\vegag\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Conv2d' object has no attribute 'fc1'